name: Run benchmarks
on:
  push:
    tags:
      - 'v*'
jobs:
  running-bench:
    name: Run benchmark
    runs-on: [self-hosted, bench]
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Run target benchmarks
        uses: artipie/benchmarks@master
        with:
          target: "debian"
          tag: "${GITHUB_REF#refs/*/}"
  pull-request:
    name: Create PR with results
    needs: running-bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set env
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: artipie/benchmarks/adapters/pull-request@master
        with:
          tag: "${{ env.TAG }}"
          token: ${{ secrets.GITHUB_TOKEN }}
